SistemaEncuesta/SistemaEncuesta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^gestor/', include('gestor.urls', namespace='gestor')),
    url(r'^admin/', admin.site.urls),
]

SistemaEncuesta/gestor/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
app_name = 'gestor'
urlpatterns = [
    url(r'^inicio/$', views.index, name='inicio'),
    url(r'^responder/(?P<id_encuesta>[0-9]+)/$', views.responder_encuesta, name='responder_encuesta'),
    url(r'^editar/(?P<id_encuesta>[0-9]+)/$',views.editar_encuesta, name='editar_encuesta'),
    url(r'^agregar/pregunta/(?P<id_encuesta>[0-9]+)/$', views.agregar_pregunta, name='agregar_pregunta'),
    url(r'^agregar/respuesta/(?P<id_encuesta>[0-9]+)/(?P<id_pregunta>[0-9]+)/$', views.agregar_respuesta, name='agregar_respuesta'),
    url(r'^$', views.login, name='login'),
    url(r'^administracion/(?P<id_usuario>[0-9]+)/$', views.administracion, name='administrar'),
    url(r'^agregar/encuesta/(?P<id_usuario>[0-9]+)/$', views.agregar_encuesta, name='agregar_encuesta'),
    url(r'^ver/(?P<id_encuesta>[0-9]+)/$', views.ver_encuesta, name='ver'),
    url(r'^gracias/(?P<id_encuesta>[0-9]+)/$', views.gracias, name='gracias'),
    url(r'^error/$', views.error, name='error'),
	]

SistemaEncuesta/gestor/models.py
from django.db import models
from django.utils import timezone
from django import forms
# Create your models here.
class Usuario(models.Model):
	correo = models.CharField(max_length=255)
	contrasenia = models.CharField(max_length=100)

class Encuesta(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
	titulo_encuesta = models.CharField(max_length=255,)
	descripcion = models.CharField(max_length=255)
	fecha_creacion = models.DateField(auto_now_add=timezone.now().date)
	visitas = models.IntegerField(default=0)

	def __str__(self):
		return self.titulo_encuesta

class Pregunta(models.Model):
	contenido = models.CharField(max_length=255)
	encuesta = models.ForeignKey(Encuesta, null=False, on_delete=models.CASCADE)

	def __str__(self):
		return self.contenido

class Respuesta(models.Model):
	contenido = models.CharField(max_length=255)
	pregunta = models.ForeignKey(Pregunta, null=False, on_delete=models.CASCADE)

	def __str__(self):
		return self.contenido

class EncuestaRespuesta(models.Model):
	encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
	ip = models.CharField(max_length=50)

class RespuestaElegida(models.Model):
	respuesta_encuesta = models.ForeignKey(EncuestaRespuesta, on_delete=models.CASCADE)
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
	respuesta = models.ForeignKey(Respuesta, on_delete=models.CASCADE)

SistemaEncuesta/gestor/views.py
from django.shortcuts import *
from django.http import *
from gestor.models import *
from django.template import *
from django.urls import *
import json
import urllib
from SistemaEncuesta import *
# Create your views here.

#Aqui se realiza el login
def login(request):
    if request.method == 'POST' :
        try:
            usuario = Usuario.objects.get(correo=request.POST.get('email', ''), contrasenia=request.POST.get('password',''))
            return redirect('/gestor/administracion/' + str(usuario.id) + '/')
        except:
            return redirect('/gestor/')
    else:
        contexto = {}
        return render(request, 'Login.html', contexto)

def administracion(request, id_usuario):
    if request.method == 'POST' :
        obtener_usuario = Usuario.objects.get(id=id_usuario)
        obtener_enc = Encuesta.objects.filter(usuario=obtener_usuario)
        opcion = request.POST.get('eliminar','')
        if opcion == 'Eliminar Seleccionados' :    
            for el1 in obtener_enc:
                eliminar = request.POST.get('chech_enc' + str(el1.id), '')
                if eliminar != '' :
                    enc_eliminada = Encuesta.objects.get(id=int(eliminar))
                    enc_eliminada.delete()  
            return redirect('/gestor/administracion/' + str(id_usuario))
        for enc in obtener_enc:
            opcion2 = request.POST.get('opcion' + str(enc.id))
            if opcion2 == 'Editar' :
                return redirect('/gestor/editar/' + str(enc.id))
            elif opcion2 == 'Ver' :
                return redirect('/gestor/ver/' + str(enc.id))
    else:
        contexto = {}
        obtener_usuario = Usuario.objects.get(id=id_usuario)
        contexto['usuario'] = obtener_usuario
        obtener_enc = Encuesta.objects.filter(usuario=obtener_usuario)
        contexto['encuesta'] = obtener_enc
        return render(request, 'Administrador.html', contexto)

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

########RESPONDER ENCUESTA########################
def responder_encuesta(request, id_encuesta):
    if request.method == 'POST':
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())

        if result['success'] :
            ip_usuario = obtenerIp(request)
            
            pasar = True
            resp = EncuestaRespuesta.objects.filter(ip=ip_usuario)
            for elemento in resp :
                if elemento.ip == ip_usuario:
                    pasar = False
                    break

            if pasar == False :
                return redirect('/gestor/error/')
            else:
                #puedes continuar
                enc = Encuesta.objects.get(id=id_encuesta)
                visitas = enc.visitas
                visitas = visitas + 1
                enc.visitas = visitas
                enc.save()
                enc_resp = EncuestaRespuesta(encuesta=enc, ip=ip_usuario)
                enc_resp.save()
                id_enc = enc_resp.id
                preguntas = Pregunta.objects.filter(encuesta=enc)
                
                try:
                    for el1 in preguntas:
                        opcion_elegida = request.POST.get('Radio' + str(el1.id), '')
                        if opcion_elegida != '':
                            get_encuesta_respuesta = EncuestaRespuesta.objects.get(id=id_enc)
                            respuesta = Respuesta.objects.get(id=int(opcion_elegida))
                            eleccion = RespuestaElegida(respuesta_encuesta=get_encuesta_respuesta, pregunta=el1, respuesta=respuesta)
                            eleccion.save()
                    return redirect('/gestor/gracias/' + str(id_encuesta))  
                except:
                    return render(request, 'ResponderEncuesta.html', contexto)
        else:
            return redirect('/gestor/responder/' + str(id_encuesta) + '/')
    else:
        contexto = {}
        encuesta = Encuesta.objects.get(id=id_encuesta)
        contexto["encuesta"]=encuesta
        preguntas = Pregunta.objects.filter(encuesta=encuesta)
        
        list_preguntas=[]
        list_resp=[]

        for el in preguntas:
            list_preguntas.append(el)
            respuestas = Respuesta.objects.filter(pregunta=el).order_by('id')
            for el2 in respuestas:
                list_resp.append(el2)

        contexto["pregunta"]=list_preguntas
        contexto["respuesta"]=list_resp
        return render(request, 'ResponderEncuesta.html', contexto)

#########EDITAR ENCUESTA################
def editar_encuesta(request, id_encuesta):
    if request.method == 'POST':
#########Aqui se agregan y eliminan las respuestas########################################################
        obtener_enc = Encuesta.objects.get(id=id_encuesta)
        obtener_preg = Pregunta.objects.filter(encuesta=obtener_enc)
        for el1 in obtener_preg :
            accion2 = request.POST.get('btn_res' + str(el1.id), '')
            if accion2 == 'Agregar respuesta':
                return redirect('/gestor/agregar/respuesta/' + id_encuesta + '/' + str(el1.id) + '/')
            elif accion2 == 'Eliminar respuestas' :
                obtener_resp = Respuesta.objects.filter(pregunta=el1)
                for el2 in obtener_resp :
                    eliminar = request.POST.get('check_res' + str(el2.id),'')
                    if eliminar != '' :
                        resp_eliminada = Respuesta.objects.get(id=el2.id)
                        resp_eliminada.delete()
                return redirect('/gestor/editar/' + id_encuesta + '/')
#########Aqui se agregan preguntas, se guarda la edicion de le encuesta, se elimina y cancela edicion##############
        accion = request.POST.get("btn", '')
#########Guardar edicion de la encuesta################################################################
        if accion == 'Guardar':
            obtener_encuesta = Encuesta.objects.get(id=id_encuesta)
            enc = request.POST.get('id_enc' + str(obtener_encuesta.id))
            obtener_encuesta.titulo_encuesta = enc
            obtener_encuesta.save()
            obtener_preguntas = Pregunta.objects.filter(encuesta=obtener_encuesta)

            for elemento_pregunta in obtener_preguntas:
                pregunta_modificada = request.POST.get('id_pr' + str(elemento_pregunta.id), '')
                if pregunta_modificada != '' :
                    elemento_pregunta.contenido = pregunta_modificada
                    elemento_pregunta.save()

                    obtener_respuestas = Respuesta.objects.filter(pregunta=elemento_pregunta)
                    
                    for elemento_respuesta in obtener_respuestas:
                        respuesta_modificada = request.POST.get('id_res' + str(elemento_respuesta.id), '')
                        if respuesta_modificada != '' :
                            elemento_respuesta.contenido = respuesta_modificada
                            elemento_respuesta.save()
            return redirect('/gestor/administracion/'+ str(obtener_encuesta.usuario.id) + '/')
#########Agregar pregunta################################################################################
        elif accion == 'Agregar nueva pregunta': 
            return redirect('/gestor/agregar/pregunta/' + id_encuesta + '/')
#########Eliminar preguntas################################################################################
        elif accion == 'Eliminar preguntas':
            obtener_encuesta = Encuesta.objects.get(id=id_encuesta)
            obtener_preguntas = Pregunta.objects.filter(encuesta=obtener_encuesta)
            for elemento_pregunta in obtener_preguntas:
                eliminar = request.POST.get('check_pr' + str(elemento_pregunta.id), '')
                if eliminar != '':
                    preg_eliminada = Pregunta.objects.get(id=int(eliminar))
                    preg_eliminada.delete()
            return redirect('/gestor/editar/' + id_encuesta + '/')
        elif accion == 'Cancelar':
            obtener_enc = Encuesta.objects.get(id=id_encuesta)
            return redirect('/gestor/administracion/'+ str(obtener_enc.usuario.id) + '/')
            
    contexto = {}
    lista_respuesta = []
    get_encuesta = Encuesta.objects.get(id=id_encuesta)
    contexto['encuesta'] = get_encuesta
    get_pregunta = Pregunta.objects.filter(encuesta=get_encuesta)
    contexto['pregunta'] = get_pregunta
    for el in get_pregunta:
        get_respuesta = Respuesta.objects.filter(pregunta=el).order_by('id')
        lista_respuesta.append(get_respuesta)

    contexto['respuesta'] = lista_respuesta
    contexto['id_encuesta'] = id_encuesta
    return render(request, 'EditarEncuesta.html', contexto)

########AGREGAR PREGUNTA########################
def agregar_pregunta(request,id_encuesta):
    contexto = {}
    obtener_encuesta = Encuesta.objects.get(id=id_encuesta)
    contexto['encuesta'] = obtener_encuesta

    if request.method == 'POST':
        texto_pregunta = request.POST.get('texto_pregunta', '')
        if texto_pregunta != '':
            nueva_pregunta = Pregunta(contenido=texto_pregunta, encuesta=obtener_encuesta)
            nueva_pregunta.save()
            return redirect('/gestor/editar/' + id_encuesta + '/')
        else:
            return redirect('/gestor/editar/' + id_encuesta + '/')
    return render(request, 'IngresarPregunta.html', contexto)

########AGREGAR RESPUESTA########################
def agregar_respuesta(request, id_encuesta, id_pregunta):
    contexto = {}

SistemaEncuesta/gestor/templates/Administrador.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/app.css">
    <title>Página del administrador</title>  
  </head>
  <!--Fin de head  -->

  <body>
    <header id="header-container">
      <div class="container"> 
        <a href="/gestor/administracion/{{ usuario.id }}">
        <h2>Encuestas UES</h2>
        </a>
      </div>
    </header>
    <!--Fin de header -->

    <div class="container" id="admin-container">
        <div class="row">
          <div class="col-md-10">
            <h2>
                Sitio del administrador.
            </h2>
          </div>
          <div class="col-md-2" align="right">
            <a href="/gestor/">Cerrar Sesion</a>
          </div>  
        </div>
        <div class="row">
          <div class="col-md-5"></div>
    			<div id="link-admin-container" class="col-md-7">
    			<a href="/gestor/agregar/encuesta/{{ usuario.id }}">
    			    <h5>Crear encuesta</h5>
    			</a>
  			 </div>
		    </div>
          <div class="row">
          <form action="{% url 'gestor:administrar' usuario.id %}" method="POST">
          {% csrf_token %}
  	        <div class="container">	
  			  <h2>Encuestas existentes:</h2>                                                     
  			  <div class="table-responsive">          
  			  <table class="table">
  			    <thead>
  			      <tr>
  			      	<th width="50px"></th>
  			        <th width="50px">ID</th>
  			        <th>Nombre de encuesta</th>
  			        <th width="50px">Ver</th>
  			        <th width="50px">Editar</th>
  			        <th width="50px">Visitas</th>
  			      </tr>
  			    </thead>
  			    <tbody>
  				{% if encuesta %}
  				  {% for enc in encuesta %}
  			      <tr>
  			      	<td><input type="checkbox" name="chech_enc{{ enc.id }}" value="{{ enc.id }}"></td>
  			        <td>{{ enc.id }}</td>
  			        <td>{{ enc.titulo_encuesta }}</td>
  			        <td><input type="submit" value="Ver" name="opcion{{ enc.id }}" class="btn btn-default"></td>
  			        <td><input type="submit" value="Editar" name="opcion{{ enc.id }}" class="btn btn-default"></td>
  			        <td>{{ enc.visitas }}</td>
  			      </tr>
  			      {% endfor %}
  				{% endif %}
  			    </tbody>
          </table>
            </div>
              </div>
              <div class="row">
                <div class="col-md-3 offset-9" align="right">
                  <input type="submit" class="btn btn-danger" value="Eliminar Seleccionados" name="eliminar">
                </div>
              </div>
  		    </form>
  		</div>        
    </div>

    <footer id="footer-container"> <!--Pie de pagina--> 
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <p> &copy;  2017. Todos los derechos reservados</p>
                </div>
            </div>
            <div class="row"> 
                <div class="col-sm-8">
                    Facultad de Ingeniería y arquitectura. Universidad de El Salvador.
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <!--Requerido para Bootstrap-->
  </body>
</html>

SistemaEncuesta/gestor/templates/EditarEncuesta.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/app.css">
    <title>Editar encuesta</title>  
  </head>
  <!--Fin de head  -->

  <body>
    <header id="header-container">
      <div class="container"> 
        <a href="/gestor/administracion/{{ encuesta.usuario.id }}">
        <h2>Encuestas UES</h2>
        </a>
      </div>
    </header>
    <!--Fin de header -->
    

    <div class="encuesta-container">
      <form action="{% url 'gestor:editar_encuesta' encuesta.id %}" id="pregunta-form" method="POST">
      {% csrf_token %}
      <input type="hidden" id="id_encuesta" name="id_encuesta" value="{{ encuesta.id }}">
      	<div class="container">
			<div class="row"> <!-- Contenedor del titulo de la encuesta-->
		   	 		<input type="text" id="nombre-encuesta" class="form-control row col-lg-10 offset-1" placeholder="Titulo de la encuesta" value="{{encuesta.titulo_encuesta}}" name="id_enc{{ encuesta.id }}">
		    </div>
	    </div>
	    {% for pr in pregunta %}
      	<div class="pregunta-container">
      		<div class="container"> <!-- Contenedor de la pregunta, incluye el boton agregar respuesta-->
	        <div class="row" id="texto-pregunta">
			    <div class="input-group col-sm-8">
			      <span class="input-group-addon">
			        <input type="checkbox" name="check_pr{{ pr.id }}" value="{{ pr.id }}">
			      </span>
			      <input type="text" class="form-control" placeholder="Titulo de la pregunta" style="text-align: center" name="id_pr{{ pr.id }}" value="{{ pr.contenido }}">
			    </div>
			</div>
			</div>
			{% for aux in respuesta %}
				{% for res in aux %}
					{% if res.pregunta.id == pr.id %}
				<div class="container">
					<div class="row">
					    <div class="input-group col-sm-8">
					      <span class="input-group-addon">
					        <input type="checkbox" name="check_res{{ res.id }}" value="{{ res.id }}">
					      </span>
					      <input type="text" class="form-control" placeholder="Titulo de la respuesta" value="{{ res.contenido }}" name="id_res{{ res.id }}">
					    </div>
			        </div>
		        </div>
		        	{% endif %}
				{% endfor %}
			{% endfor %}
			<br>
			<div class="container">
		        <div class="row">
		        	<div class="col-sm-4">
						<input type="submit" class="btn btn-secondary" value="Agregar respuesta" name="btn_res{{ pr.id }}">
			  				  <!--Boton agregar respuesta-->
						<input type="submit" class="btn btn-secondary" value="Eliminar respuestas" name="btn_res{{ pr.id }}">
			  				  <!--Boton eliminar selecciones-->
					</div>
		        </div> 	
		    </div>		
		{% endfor %}
      	</div> <!-- Termina contenedor de la pregunta-->
      	<br>
		<div class="container">
		    <div class="row">
		    <div class="col-sm-9">
		    	<input type="submit" class="btn btn-primary" value="Agregar nueva pregunta" name="btn">
				<input type="submit" class="btn btn-warning" value="Eliminar preguntas" name="btn">
		    </div>
			<div class="col-sm-3">
				<input type="submit" class="btn btn-success" value="Guardar" name="btn">
				<input type="submit" class="btn btn-danger" value="Cancelar" name="btn">
			</div>
	    </div>
      </form> 
    </div>
    <!--Fin pregunta 1-->
	<footer> <!--Pie de pagina--> 
      <div class="container">
        <div class="row">
          <div class="col-sm-4">
            <p> &copy;  2017. Todos los derechos reservados</p>
          </div>
        </div>
        <div class="row"> 
          <div class="col-sm-8">
            Facultad de Ingeniería y arquitectura. Universidad de El Salvador.
          </div>
        </div>
      </div>
    </footer>


    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <!--Requerido para Bootstrap-->
  </body>
</html>

SistemaEncuesta/gestor/templates/IngresarEncuesta.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  	<link rel="stylesheet" href="/static/css/app.css">
    <title></title>
  </head>
  <!--Fin de head  -->

  <body>
    <header id="header-container">
      <div class="container"> 
        <a href="/gestor/administracion/{{ usuario.id }}">
        <h2>Encuestas UES</h2>
        </a>
      </div>
    </header>

    <form action="{% url 'gestor:agregar_encuesta' usuario.id %}" style="margin-top: 5em" method="POST">
    {% csrf_token %}
      	<div class="container">
	        <div class="row">
	        <div class="col-md-1"></div>
	          <div class="col-md-4">
	              <label>Nombre de encuesta:</label>
	          </div>
	        </div>
	        <div class="row">
	        <div class="col-md-1"></div>
	          <div class="col-xl-9">
	            <input type="text" class="form-control" placeholder="Encuesta" name="encuesta">
	          </div>
	        </div>
	        <div class="row">
	        <div class="col-md-1"></div>
	          <div class="col-md-4">
	              <label>Descripción:</label>
	          </div>
	        </div>
	        <div class="row">
	        <div class="col-md-1"></div>
	          <div class="col-xl-9">
	            <input type="text" class="form-control" placeholder="Descripción" name="descripcion">
	          </div>
	        </div>
	        <div class="row">
	        	<div class="col-md-8"></div>
	          <div class=" col-md-2" align="right"><!--Boton enviar-->
	             <input type="submit" class="btn btn-success" id="btn-enviar" style="margin-top: 1em;" value="Enviar"> 
	          </div>
	        </div>
   		</div>
    </form>
    <footer> <!--Pie de pagina--> 
      <div class="container">
        <div class="row">
          <div class="col-sm-4">
            <p> &copy;  2017. Todos los derechos reservados</p>
          </div>
        </div>
        <div class="row"> 
          <div class="col-sm-8">
            Facultad de Ingeniería y arquitectura. Universidad de El Salvador.
          </div>
          <div class="col-sm-4 offset-">
            <a href="#">  <!-- Link para iniciar sesion como administrador-->
              Iniciar sesion como Administrador
            </a>
          </div>
        </div>
      </div>
    </footer>
		
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <!--Requerido para Bootstrap-->
  </body>
  

</html>